MyFavoriteMemesEB/MyFavoriteMemesEB/Models/HomeViewModel.cs
using System.Collections.Generic;

namespace MyFavoriteMemesEB.Models
{
    public class HomeViewModel
    {
        public List<ImageModel> MemeList { get; set; }

        public MemeModel SubmitMeme { get; set; }
    }
}

MyFavoriteMemesEB/MyFavoriteMemesEB/Controllers/HomeController.cs
using MyFavoriteMemesEB.Models;
using System.Collections.Generic;
using System.Web.Mvc;

namespace MyFavoriteMemesEB.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            var model = new HomeViewModel()
            {
                MemeList = new List<Models.ImageModel>
                {
                    new Models.ImageModel
                    {
                        MemeId = 1,
                        ImageUrl = "http://i.dailymail.co.uk/i/pix/2016/03/18/15/324D202500000578-3498922-image-a-33_1458315465874.jpg"
                    },

                    new Models.ImageModel
                    {
                        MemeId = 2,
                        ImageUrl = "http://i.dailymail.co.uk/i/pix/2016/03/18/15/324D202500000578-3498922-image-a-33_1458315465874.jpg"
                    },
                    new Models.ImageModel
                    {
                        MemeId = 3,
                        ImageUrl = "http://i.dailymail.co.uk/i/pix/2016/03/18/15/324D202500000578-3498922-image-a-33_1458315465874.jpg"
                    }
                }
            };

            return View(model);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MyFavoriteMemesEB/MyFavoriteMemesEB/Controllers/ImageProcessingController.cs
using MyFavoriteMemesEB.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyFavoriteMemesEB.Controllers
{
    public class ImageProcessingController : Controller
    {
        // GET: ImageProcessing
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ProcessMeme(HomeViewModel model)
        {
            var processedMeme = new ProcessMemeViewModel()
            {
                TopText = model.SubmitMeme.TopText,
                BottomText = model.SubmitMeme.BottomText,
                ImageUrl = model.SubmitMeme.ImageUrl
            };

            return View(processedMeme);
        }
    }
}

MyFavoriteMemesEB/MyFavoriteMemesEB/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MyFavoriteMemesEB/MyFavoriteMemesEB/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MyFavoriteMemesEB/MyFavoriteMemesEB/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

@model MyFavoriteMemesEB.Models.HomeViewModel

<div class="jumbotron">
    <h1>My Favorite Memes</h1>
    <p class="lead">There's a whole internet of images out there.  Make a Meme out of it.</p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Upload an image</h2>
        <p>
            Select an image you want to upload.
        </p>
        <p>
            @using (Html.BeginForm("UoloadImage", "ImageProcessing"))
            {
                <input type="file" name="FileUpload" />
                <input type="text" name="FileName" value="FileName" style="margin-top:10px;"/> <br />
                <input type="submit" name="submit" id="submit" value="Submit" style="margin-top:10px;" />
            }
        </p>
    </div>
    <div class="col-md-4">
        <h2>Select an image</h2>
        <div style="width:900px">
            @using (Html.BeginForm("ProcessMeme", "ImageProcessing", FormMethod.Post, new { id = "memeForm" }))
            {
                    <div style="float:left; overflow-y: scroll; overflow-x: hidden; width:50%">
                        <ul id="council-slider" style="margin: 0 auto; list-style: none; min-height: 300px; max-height: 400px;">
                            @foreach (var image in Model.MemeList)
                            {
                                <li class="select-image" style="display:block; border:50px solid #ffffff">
                                    <img id="@image.MemeId" src="@image.ImageUrl" style="float: left; height: auto;width: 75%; margin: 5px" />
                                    <div style="height: 30px; width: 100px; float: left;" />
                                    <input type="hidden" value="@image.MemeId" />
                                    <br />
                                </li>
                            }
                        </ul>
                </div>

                <div style="float:left; width:35%;padding-left:10px">
                    @Html.LabelFor(m => m.SubmitMeme.TopText)<br />
                    @Html.TextBoxFor(m => m.SubmitMeme.TopText)<br />
                    
                    @Html.LabelFor(m => m.SubmitMeme.BottomText)<br />
                    @Html.TextBoxFor(m => m.SubmitMeme.BottomText)<br />
                    
                    @Html.HiddenFor(m => m.SubmitMeme.MemeId)
                    @Html.HiddenFor(m => m.SubmitMeme.ImageUrl)
                    <input type="submit" value="Generate" style="margin-top:10px;" onclick="validateMemeGen()"/>
                </div>
            }
        </div>
        </div>
</div>